language: node_js
branches:
  only:
  - master
addons:
  sonarcloud:
    organization: "jo3-w3b-d3v"
    token:
      secure: "1072ee0d01a9c38e8ebe63de16a01abca0be1543" # encrypted value of your token
before_install:
  - npm install
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- npm run test
- sonar-scanner